STATUS_EXCLUDED = ["Backlog"]

CANONICAL_ORDER = [
    "New", "Open", "Opened", "Reopened",
    "Vision", "Initiative in Backlog", "Backlog", "Postponed",
    "To Analyse", "Analyse", "Analyse Pending",
    "In Analyse", "Analysis ongoing", "Under investigation", "Qualification",
    "Awaiting BP approval",
    "Waiting for priority",
    "Ready", "Ready for Business", "Ready for sprint",
    "Selected for Development", "To Development",
    "Ready for Review",
    "To Do",
    "Implementing", "In Progress", "Initiative in Progress",
    "Blocked internally", "Blocking", "Blocked externally",
    "Waiting for support", "Waiting for Supplier",
    "Waiting for customer", "Waiting for feedback", "Waiting Feedback",
    "Waiting for approval", "Waiting for Validation", "Pending",
    "Pull Request", "Under review", "In Review",
    "Ready for Test", "In Test",
    "Ready for Validation", "In Validation", "To validation",
    "Ready for acceptance", "In acceptance",
    "Ready to deploy Test",
    "Waiting for Go/NoGo",
    "Ready for release", "Deployed",
    "Resolved", "Completed", "Issue Completed", "Closed", "Done",
    "Rejected", "Declined", "Canceled", "Failed",
]
